### ISSUE TITLE
Allow setting which outlets are reset only and which aren't

### ISSUE THREAD

**Issue by Hans-Solo-Dolo** [michaelahern/homebridge-wattbox-ip#10]
Would like to be able to choose which outlets are reset only. Currently all are either reset or not. If I choose not, it will not let me power cycle a device that is reset only on the watt box itself. If I choose reset only in the plugin, I cannot turn off an individual outlet, it will only reboot.

**Comment by michaelahern** [comment]
The way I've been handling this on my Wattbox has been by configuring specific outlets on the Wattbox itself to be reset only. This way, there's no issue with outlet configs being out of sync between Homebridge and the Wattbox. When an outlet is configured on the Wattbox as reset only, a power on/off event from HomeKit/Homebridge will reset the outlet.

If you can't configure this via the Wattbox UI or with your installer, you can do this via the same API that the plugin uses. Take a look at the [API Docs](https://github.com/michaelahern/homebridge-wattbox-ip/blob/main/specs/SnapAV_Wattbox_API_V2.4.pdf). You'd need to run the following command using netcat or ssh:

```
!OutletModeSet=OUTLET,2
```

Where OUTLET is the outlet number and 2 is the mode value for reset only..

**Comment by michaelahern** [comment]
Support for this has been added in v1.0.0..

**Comment by Hans-Solo-Dolo** [comment]
Thank you
