### ISSUE TITLE
Add ability to cycle outlets?

### ISSUE THREAD

**Issue by dficken** [michaelahern/homebridge-wattbox-ip#2]
In addition to the on/off control, could you add an option (specify in settings) for a control that cycles the outlet?

**Comment by michaelahern** [comment]
Added a couple options in the latest version to force outlets on a device to either be read only (on/off in HomeKit will have no effect) or reset only (any on/off action in HomeKit sends a reset action to the wattbox outlet, which always brings the outlet to an off state, then on state, using any configured delays on the outlet). Please give it a spin..

Would note, this is a per-WattBox device configuration option at the moment, not a per outlet configuration. Will consider per outlet configs in a future release, but want to try and avoid making the config too complex at this stage..
